export const WATCH_APP_PACKAGE_NAME = "" // Set WATCH_APP_PACKAGE_NAME
export const PHONE_APP_FINGERPRINT = "" // Set WATCH_APP_FINGERPRINT
export const PHONE_APP_PACKAGE_NAME = "" // Set PHONE_APP_PACKAGE_NAME
export default {WATCH_APP_PACKAGE_NAME,PHONE_APP_FINGERPRINT,PHONE_APP_PACKAGE_NAME}